name: Build and deploy ASP.Net Core app to Azure Web App - nationalbank-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore src/NationalBank.API/NationalBank.API.csproj

      - name: Build
        run: dotnet build src/NationalBank.API/NationalBank.API.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish src/NationalBank.API/NationalBank.API.csproj -c Release -o published

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-app
          path: published

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CF1F80A6D1B34FB88D6F430EAD556590 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_960714553C38486DA6A3919A86FE91AC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_097A22F4F8704566AC5BDDEA8D9A0A63 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nationalbank-api'
          slot-name: 'Production'
          package: '.'
